### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by sseken** [DFRobot/DFRobot_MLX90614#4]
I'm testing a MLX90614 (SEN0263, DFROBOT). MLX90614 module works properly on Arduino Uno or Mega. Howerver, the device cannot begin on Arduino Due (https://store.arduino.cc/products/arduino-due) with the message "Communication with device failed, please check connection" when I run "getData" code (https://github.com/DFRobot/DFRobot_MLX90614/blob/master/examples/getData/getData.ino). I connected 3.3V, GND, SCL, SDA as shown in the figure in your direction page (https://www.dfrobot.com/product-1745.html). Would you give me some advice to solve this issue?

**Comment by qsjhyy** [comment]
Firstly, it works on Uno or Mega, indicating that the sensor and library are mostly fine.

However, it fails to initialize on Due, indicating a problem with the I2C communication. It could be an issue with the wiring for this session or a difference in the I2C bus. You can begin by using the onboard I2C address scanning example to ensure the connections are correct.

Finally, our module library indeed does not require compatibility testing for Arduino Due. You can examine the differences in the I2C driver and library and make modifications for compatibility.

**Comment by qsjhyy** [comment]
There is no reply for too long, and it can be reopened if necessary.
